version: "3.8"

services:
  blogotypo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blogotypo-app
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - blogotypo-network
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test:
        ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongodb:
    image: mongo:7-jammy
    container_name: blogotypo-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: Blogotypo
    ports:
      - "27017:27017"
    networks:
      - blogotypo-network
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  blogotypo-network:
    driver: bridge

volumes:
  mongo-data:
